services:
  - type: web
    name: ytdlp-downloader
    env: python

    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y ffmpeg

    startCommand: gunicorn --workers 1 --threads 8 --timeout 0 app:app

    autoDeploy: true
